replicaCount: 2

image:
  repository: vikashnigam/springboot-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  SPRING_DATASOURCE_URL: "jdbc:mysql://springboot-mysql.cdu0wim8ibl6.ap-southeast-1.rds.amazonaws.com:3306/springboot-mysql"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "Welcome123"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: springboot-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

prometheus:
  enabled: true
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'springboot-app'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['springboot-app.default.svc.cluster.local:8080']
